export const SET_TEST = 'SET_TEST'
export const SET_BY_ME_COURSE_LIST = 'SET_BY_ME_COURSE_LIST'
export const SET_COURSE_ID_LIST = 'SET_COURSE_ID_LIST'
export const GET_SCHOOL_TEACHER_YIN_JIN_LIST = 'GET_SCHOOL_TEACHER_YIN_JIN_LIST'
export const GET_ALL_SCHOOL_COURSE_SCORE_YIN_JIN_LIST =
  'GET_ALL_SCHOOL_COURSE_SCORE_YIN_JIN_LIST'
export const GET_GAO_DI_PING_COURSE_SCORE_YIN_JIN =
  'GET_GAO_DI_PING_COURSE_SCORE_YIN_JIN'
export const GET_SCORE_COUNT_ONE_YIN_JIN_LIST =
  'GET_SCORE_COUNT_ONE_YIN_JIN_LIST'
export const GET_ALL_STUDY_PROGRESS_ONE_YIN_JIN_LIST =
  'GET_ALL_STUDY_PROGRESS_ONE_YIN_JIN_LIST'
export const GET_DATA_STATISTICE_ONE_YIN_JIN_LIST =
  'GET_DATA_STATISTICE_ONE_YIN_JIN_LIST'
export const GET_FIND_RECORD_TABLE_ONE_YIN_JIN_LIST =
  'GET_FIND_RECORD_TABLE_ONE_YIN_JIN_LIST'
export const GET_EXAM_INATION_TWO_PAPER_ONE_YIN_JIN_LIST =
  'GET_EXAM_INATION_TWO_PAPER_ONE_YIN_JIN_LIST'
