export default {
  byMeCourseList: [],
  byMeCourseTotal: '',
  courseIdList: {},
  dialogVisible: false,
  schoolTeacherTotal: null,
  schoolTeacherList: [],
  allCourseScoreTotal: null,
  allCourseScoreList: [],
  courseScoreSumYinJinObj: {},
  scoreCountOneYinJinList: null,
  allStudyProgressTotalOneYinJin: null,
  allStudyProgressListOneYinJin: [],
  eChartsChartVoMap: null,
  eChartsCountVoMap: null,
  findRecordTotalOneYinJin: null,
  findRecordListOneYinJin: [],
  examinationTwoListOneYinJin: [],
}
