export const SET_TEST = 'SET_TEST'
export const SET_ALL_EXAM_AMINATION_SUBJECT = 'SET_ALL_EXAM_AMINATION_SUBJECT'
export const SET_EXAM_INATION_TWO_LIST = 'SET_EXAM_INATION_TWO_LIST'
export const BY_EXAM_INATION_ID = 'BY_EXAM_INATION_ID'
export const ADD_EXAM_INATION_RECORD = 'ADD_EXAM_INATION_RECORD'
export const GET_BY_RECORD_ID_CE_BIAN_LAN = 'GET_BY_RECORD_ID_CE_BIAN_LAN'
export const GET_FIND_RECORD_LIST = 'GET_FIND_RECORD_LIST'
export const GET_BY_EXAM_SUBJECT_CHICES_RELEASED =
  'GET_BY_EXAM_SUBJECT_CHICES_RELEASED'
